# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]



arr1 = np.array([height])
arr2 = np.array([weight])

bmi = ((arr2 / arr1 ** 2) * 730)
bmi


array([[16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
        21.32943755, 22.06222222]])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [6]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass


def makeMatrix(low, high,data_type = float):
    a = np.random.uniform(0, low, (high, high))
    print(a)
    
low = 3
high = 5


makeMatrix(low, high, int)

[[2.26232523 2.08058028 1.95902389 0.58718849 0.2199772 ]
 [1.06348142 0.28867274 1.00747609 0.1906884  1.17731412]
 [2.26971779 0.87322384 1.59697289 0.4731139  0.04259948]
 [2.26329551 2.59853066 1.14568845 1.68413851 0.95016059]
 [0.14370429 2.68067717 1.27998382 2.9842562  0.57314818]]


In [10]:
def makeMatrix2(low, high, rows, columns, data_type = 'float'):
    if data_type == 'int':
        a = np.random.randint(low, high, (rows, columns))
    else:   
     a = np.random.uniform(low, high, (rows, columns) dtype = int64)
    return(a)


SyntaxError: invalid syntax (<ipython-input-10-5c97447e0d7c>, line 5)

In [9]:
makeMatrix2(5,7,4,4,'int')

array([[6, 6, 5, 6],
       [5, 6, 6, 5],
       [6, 5, 6, 5],
       [5, 6, 5, 5]])

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [11]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [28]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols =np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    
    return data
bs2018 = load_data('files/redsox_2018_hitting.txt')
bs2017 = load_data('files/redsox_2017_hitting.txt')
names17 = bs2017['SLG']
names18 = bs2018['SLG']
print(np.mean(names17))
print(np.mean(names18))
print(f'\n', "2017 has the better SLG of the two years ")

0.39334783
0.3875

 2017 has the better SLG of the two years 
